### PR TITLE
Prevent using simplecov_json_formatter 0.1.4, which seems to break co…

### PR DESCRIPTION
**Pull request by jcoyne**
…declimate

### CODE REVIEW

**Comment by justinlittman** [comment]
Given that fix is forthcoming shortly, do you want to close this?

**Comment by jcoyne** [comment]
This blocks the PR that allows Laura to write an integration test for virtual objects, so I'd probably not wait.

**Review by justinlittman — APPROVED** [review]
Approve, but as an alternative, I'm happy to use my admin superpowers in the meantime.

**Comment by jcoyne** [comment]
Oh, well please do that instead.

**Comment by jcoyne** [comment]
This doesn't seem to be a problem anymore.

**Pull request closed without merging**
