### PR TITLE
Add ability to print out version of client

### PR DESCRIPTION
**Pull request by mjgiarlo**
## Why was this change made?

To make it easier for users to know what version of the client they are running.

## How was this change tested?

Run locally + CI

## Which documentation and/or configurations were updated?

README

### CODE REVIEW

**Comment by jcoyne** [comment]
Rubocop found a few concerns.

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 
> Rubocop found a few concerns.

got 'em

**Comment by jcoyne** [comment]
I think you missed one.

**Comment by mjgiarlo** [comment]
@jcoyne why run `rubocop --auto-gen-config` once when you can run it twice?

**Comment by mjgiarlo** [comment]
@jcoyne I ran rubocop three times, all green.

**Pull request merged**
