### PR TITLE
Use the Connection in the model deposit

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?
So that connection setup is only done one way.

## Was the documentation (README, wiki) updated?
n/a

### CODE REVIEW

**Comment by jcoyne** [comment]
@ndushay where else do you think it should be used where it isn't already?

**Comment by ndushay** [comment]
@jcoyne I don't know this code base -- I'm just suggesting that if the intent is for this repo to do more than just deposit objects, then perhaps the notion of a connection shouldn't be in a class deposit/model_xxx.   Would the connection be useful to any sdr-api action, or is this a special connection because it's a deposit?  If the later, could the naming of it make that clearer, or some comments?  If the former, should the connection be elsewhere?

**Comment by jcoyne** [comment]
@ndushay I thought this was the only instance where it wasn't using the Connection. I'm not sure what you're asking for.

**Comment by mjgiarlo** [comment]
It now sounds like @ndushay and @jcoyne are on the same page re: whether the new `Connection` class should be used elsewhere. I'm glad the question was asked whether this is/was an opportunity to increase consistency across the codebase, and I'm glad we've now achieved said consistency!

**Comment by ndushay** [comment]
@jcoyne - i do not know this code base.  I am looking at the PR from the diffs.  I don't take it on as my responsibility, as reviewer, to review the whole code base.  

I figured since you are much more knowledgible about this code base that you might be able to contextualize things better, which is why I phrased my comment as a naive question.  Your responses tell me that 

- we're not communicating very efficiently this way
- there is a Connection class elsewhere.  

I don't know if we will likely need to have a similar token in other contexts. 

This is also why I didn't request changes.  Perhaps you want a different reviewer.

**Comment by jcoyne** [comment]
There is only one Connection class https://github.com/sul-dlss/sdr-client/blob/master/lib/sdr_client/connection.rb and this PR updates the code so that all classes use it.

**Pull request merged**
